### ISSUE TITLE
Autoloot

### ISSUE THREAD

**Issue by Meireffer** [Reetus/ClassicAssist#1]
Is Autoloot considered in this project? Just as it was in original UOSteam?

**Comment by Reetus** [comment]
It can/could, I haven't put too much though into it as yet.

You want it like UOSteam where you can select which properties it auto loots?

**Comment by Meireffer** [comment]
If it's possible, yeah. The way it works in UOSteam is quite good.

**Comment by Reetus** [comment]
I've added to the TODO list, guesstimated time frame is 2 weeks.

**Comment by Reetus** [comment]
505f840c089987f265bbab4b686878f7bfcc3b6a

Report any issues you find...

**Comment by Meireffer** [comment]
First thing i noticed. 
When you have few items on loot list, it will try to loot them all at once resulting in "You must wait to perform another action" and only first item on list is looted.

**Comment by Reetus** [comment]
It shouldn't have, but may have tried to loot two corpses at once...

The delay between drag/drop requests is governed by your action delay setting...

I've wrapped it in a lock so additional corpses won't try and loot at same time...

I just pushed some changes, it you had autoloot entries with properties, you need to add the properties again.

Let me know if you run into any other problems...
