### ISSUE TITLE
bug? feature? dunno..

### ISSUE THREAD

**Issue by Apellamen** [Reetus/ClassicAssist#10]
if FindType (0x2264,-1,"backpack") :  #a random scroll
      UseType (0x2264)
      while WaitingForTarget():
            Pause (10)
      if TargetExists() :
            Target ('enemy')

The WaitingForTarget comand doesn't work for scroll casts. It might be amazing have it working for all the items either

**Comment by Reetus** [comment]
No way to know what items produce targets
