### ISSUE TITLE
Scavenger Agent not working ?

### ISSUE THREAD

**Issue by qkdefus** [Reetus/ClassicAssist#100]
Anyone got scavenger working? I cant get it to work at all : )
Even noticed some strange lag issues while having scavenger active? Might be random but went away when i ticked off scavenger

**Comment by Reetus** [comment]
More information required

**Comment by qkdefus** [comment]
Is it working on your end? To me it wont pick up any items on ground, reason i pushed the macro scavenger sample

**Comment by Reetus** [comment]
![ClassicAssist-2021-1-27-17-42-11](https://user-images.githubusercontent.com/6239195/105980142-760d1e00-60cf-11eb-86c7-f1a4ce4ce438.gif)

**Comment by qkdefus** [comment]
![ClassicAssist-2021-1-27-18-29-6](https://user-images.githubusercontent.com/4680848/106029781-b66b9c80-60cd-11eb-98a8-aff9d8cafe58.gif)

@Reetus not working here

**Comment by qkdefus** [comment]
unless you are running ClassicAsssist.Test.dll i dont see how you can have a working scavenger

**Comment by d0tsd0tsd0ts** [comment]
did u set container ?

**Comment by qkdefus** [comment]
yes, ive tried backpack, player, other containers, containers on ground

**Comment by Reetus** [comment]
What shard/client version/etc

**Comment by qkdefus** [comment]
uoforever, cuo 0.1.7.9, classicAssist 0.3.207.274

**Comment by Reetus** [comment]
Scavenger agent was checking that player had 25 stones available in order to prevent the character from being overloaded.

UOForever doesn't send the player's max weight.

![image](https://user-images.githubusercontent.com/6239195/106068820-2fa1d880-613c-11eb-81c1-09f27d2f9e41.png)

You will need to turn that option off

**Comment by qkdef** [comment]
Good Job, thank you 😀
