### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by mythril** [Reetus/ClassicAssist#101]
I am a bit bored and I was wondering if adding Linux support would be welcome?
I've not commonly used C#, so I have no idea what I'd be getting myself into, but I'll take a crack at it, so long as there is a chance that the code will be integrated into the mainline.

If you have any pointers on where I should start or any warnings please let me know.

If you have a coding standard I should follow I'll take that too.

**Comment by Reetus** [comment]
There is a branch here https://github.com/Reetus/ClassicAssist/tree/avalonia with the UI ported to Avalonia, so it can run on Linux/OSX

There is Avalonia/Mono bugs that need be to addressed, so it hasn't progressed lately, @KevinEady and myself were working on it.

**Comment by mythril** [comment]
Are there active bug reports for the bugs you mentioned w/ those projects? I don't mind working upstream if I can contribute somehow.

**Comment by Zeelot** [comment]
If you could share how to install ClassicAssist from the avalonia branch, I wouldn't mind helping debug issues :)

**Comment by Zeelot** [comment]
@Reetus sorry to bother just really hoping I can switch to ClassicAssist since it looks so much nicer than the other options! would love to help get linux fully supported if possible!

**Comment by Reetus** [comment]
Theres no developer to work on it currently
