### ISSUE TITLE
UseOnce("found") - Macro error: expected int, got str

### ISSUE THREAD

**Issue by qkdefus** [Reetus/ClassicAssist#104]
if FindType(0xf0d, -1, "backpack"):
	UseOnce("found")

**Comment by Reetus** [comment]
```py
UseType(0xf0d, -1, 'backpack')
```
https://github.com/Reetus/ClassicAssist/wiki/Actions#UseType

**Comment by qkdefus** [comment]
Whats the difference between useonce?

**Comment by KevinEady** [comment]
> Whats the difference between useonce?

[UseOnce](https://github.com/Reetus/ClassicAssist/wiki/Actions#UseOnce) requires an integer parameter, which is exactly why you get an "expected int, got str" error.

**Comment by Reetus** [comment]
UseOnce takes a itemid not a serial/alias

**Comment by KevinEady** [comment]
Also, `UseOnce` only searches for items in your backpack, and will be ignored once it's been "used", ie if you `UseOnce(0xeed)` twice, and you have two stacks of 0xeed, one will be used on the first call, and the second will be used on the second.

**Comment by Reetus** [comment]
I meant to write UseOnce


UseType(0xf0d, -1)

**Comment by qkdefus** [comment]
Thank you for clearing that up for me :)
