### ISSUE TITLE
Npc's does not register YellMsg commands

### ISSUE THREAD

**Issue by qkdefus** [Reetus/ClassicAssist#106]
YellMsg("bank")
EmoteMsg("bank")
WhisperMsg("bank")

i was under the impression using /yell commands would make npc listen at higher distance then /say

**Comment by Reetus** [comment]
What effect it has is up to the server, all I can do is set the correct speech type, which I am

![image](https://user-images.githubusercontent.com/6239195/105620222-873afe00-5e35-11eb-8928-5a2064611d67.png)


![image](https://user-images.githubusercontent.com/6239195/105620221-7a1e0f00-5e35-11eb-84d8-b008598ad2fd.png)

**Comment by qkdefus** [comment]
![](https://user-images.githubusercontent.com/6239195/105620222-873afe00-5e35-11eb-8928-5a2064611d67.png)

where do you get this ?

**Comment by Reetus** [comment]
http://ruosi.org/packetguide/index.xml

**Comment by qkdefus** [comment]
thank you
