### ISSUE TITLE
A bug and Request

### ISSUE THREAD

**Issue by comgram** [Reetus/ClassicAssist#12]
# Bug
EquipLastWeapon() is buggy. The function is not functioned.

# Request
Please add a new function to get raw gump data.
It helps more powerful scripting

Thank you in advanced.

**Comment by Reetus** [comment]
What shard are you playing? EquipLastWeapon() requires server support, when it supports it it changes to your previous weapon without disarming first...

![ClassicAssist-2020-2-17-18-17-1](https://user-images.githubusercontent.com/6239195/74645267-8bd14e00-51b2-11ea-8d73-318a5502e020.gif)

Gump internals are accessible, it's just not documented outside of the ClassicAssist source code, the following example reads the runebook entry names from the gump (atleast on the RunUO server I play)...

If you let me know what server you play on and what you're trying to do I can assist.

```python

from Assistant import Engine

def GetRunebookEntries(serial):
    entries = []
    UseObject(serial)
    if WaitForGump(0x554b87f3, 5000):
        res,gump = Engine.Gumps.GetGump(0x554b87f3)
       
        y = 60
       
        while y <= 165:
            element = gump.Pages[1].GetElementByXY(145, y)
            if element != None and element.Hue != 0:
                entries.append(element.Text)
 
            y = y + 5
           
        y = 60
 
        while y <= 165:
            element = gump.Pages[1].GetElementByXY(305, y)
            if element != None and element.Hue != 0:
                entries.append(element.Text)
               
            y = y + 5
           
    return entries          
   
entries = GetRunebookEntries(0x41b95250)
 
for x in range(len(entries)):
    SysMessage(entries[x])

```

![ClassicAssist-2020-2-17-18-32-0](https://user-images.githubusercontent.com/6239195/74646231-62192680-51b4-11ea-940b-01cea7ce2011.gif)
