### ISSUE TITLE
[Feature request] right click packets and temp ignore from view

### ISSUE THREAD

**Issue by qkdefus** [Reetus/ClassicAssist#122]

**Comment by Reetus** [comment]
More details needed

**Comment by qkdefus** [comment]
id like an option where you can right click a rechieved packet in debug menu and add it to some sort of temp ignore list where it gets hidden from packet recording view to easyer be able to identify other packets

**Comment by Reetus** [comment]
Implemented in 0.3.235.288

![ClassicAssist-2021-2-24-13-33-28](https://user-images.githubusercontent.com/6239195/108959184-0595f480-76af-11eb-9c79-4b7036a16cbd.gif)
