### ISSUE TITLE
PlaySound()'s usefulness is limited by how it auto-pauses the script.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#123]
I like that the sound file won't play again until it has finished playing, but pausing the entire script to play a sound prevents its use in scripts that need to carry out other actions while audibly alerting the player.

**Comment by qkdefus** [comment]
you can try put the sound file in a separate macro with "run in background" checked. then call the macro using PlayMacro(" ")

**Comment by Timorio** [comment]
Good idea, I'll try that.

**Comment by Timorio** [comment]
Can you share why you've decided this shouldn't be changed?

**Comment by Reetus** [comment]
It doesn't pause the script, the sound plays synchronously, ie, PlaySound ends with the sound finishes, thats the way I think it should be
