### ISSUE TITLE
Get Charges in a Runebook

### ISSUE THREAD

**Issue by ErrorU** [Reetus/ClassicAssist#125]
Is there a way to get the number of charges in a runebook? InGump doesn't seem to work because of other numbers in the book.

**Comment by Reetus** [comment]
You can using the gump parser, but the gump ID and gump layout can change between shards so you will probably need to do it yourself...

For example on OSI...

![image](https://user-images.githubusercontent.com/6239195/106844803-79fafa80-66e4-11eb-82ed-031060028f75.png)

https://www.youtube.com/watch?v=13glIgEMlgs

That video shows me using the gump parser to extract data from a crafting gump
