### ISSUE TITLE
The InRange method is inconsistent with the Distance method and Steam's implementation.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#127]
At the same distance, _if InRange( serial, 1 )_ and _if Distance( serial ) >= 1_ will return different results.  InRange's distance counts the tile in which the serial occupies as the first tile, which differs from Steam's functionality.

**Comment by qkdefus** [comment]
InRange( serial, 2 )  = Distance( serial ) < 2

**Comment by qkdefus** [comment]
```
        public static bool InRange( object obj, int distance )
        {
            int serial = AliasCommands.ResolveSerial( obj );

            if ( serial == 0 )
            {
                UOC.SystemMessage( Strings.Invalid_or_unknown_object_id );
                return false;
            }

            Entity entity = Engine.Items.GetItem( serial ) ?? (Entity) Engine.Mobiles.GetMobile( serial );

            if ( entity != null )
            {
                return entity.Distance < distance;
            }

            return false;
        }
```

**Comment by d0tsd0tsd0ts** [comment]
qkdefus did u have discord ?

**Comment by qkdefus** [comment]
sorry for the late reply, its qkdefus#0774

**Comment by d0tsd0tsd0ts** [comment]
In Steam, inrange 'serial' 'range'  function returns distance <= range

**Comment by d0tsd0tsd0ts** [comment]
Second Timorio, FindObject and FindType works inconsistent too ... 

They are using i.Distance < range too...
