### ISSUE TITLE
Issues with a shard that just "optimized" their network stack

### ISSUE THREAD

**Issue by ErrorU** [Reetus/ClassicAssist#129]
So the shard I play on recently announced some type of optimization they did on their network stack and now classicassist causes CUO (standalone version) to crash after running for a pretty short amount of time  (a few minutes) whereas right before the patch (before the server went down and came up) I could run macros for days. 

Any ideas how they could have basically disabled classicAssist from working? Maybe something to do with outbound packet rate, mouse movement, etc.. causing them to detect of classic assist?

I have not been able to pinpoint anything thus far, but it seems they figured out a way to disconnect once they detect "something" which is usually at most 10 minutes after running a macro.

Sorry for lack of detail.

**Comment by Reetus** [comment]
Can't do much without the shard name/login address/port
