### ISSUE TITLE
Backpack contents don't always update on death.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#130]
- ClassicUO Version: 0.1.7.58
- ClassicAssist Version: 0.3.218.285
- Shard: UOForever

The assistant sometimes doesn't update backpack contents on death, causing scripts to incorrectly think reagents are present, leading to erroneous behavior.  Reopening the backpack resolves this.

**Comment by d0tsd0tsd0ts** [comment]
@Reetus is it our side ? or Classic side ?
