### ISSUE TITLE
Delay when macro is setted "do not auto interrupt" and hold button

### ISSUE THREAD

**Issue by d0tsd0tsd0ts** [Reetus/ClassicAssist#138]
**Information**
- ClassicUO Version: 1.8.0
- ClassicAssist Version:  Lastest
- Client Version: 7.0.86.2

**Describe the bug**
When u hold button, macro is setted "Do not auto interrupt ", something are happening that action queue 2-4 in row and get a stuck, then 2-4 in row and got delay again... 

PS: it's happening with refresh, cure and heal pot... Something got delay that char doesnt drink pot
PS 2: I'm holding button
PS 3: It's on options tab to avoid freezes... 

**To Reproduce**
```
//Set do not auto interrupt
//Set Action Delay 600
//Set use object queue 13
if not Paralyzed("self"):
	UseType(0xf0d)
	WaitForTarget(250)
	Target("last")
```

**Expected behavior**
this should work in row as faster as possible when I hold button

**Screenshots**
![ClassicAssist-2021-3-1-2-12-12](https://user-images.githubusercontent.com/1846503/109454867-fbb81c80-7a33-11eb-81dc-16d172b23701.gif)

**Comment by Draggg85** [comment]
Holding down keys will disrupt macros with "do not auto interrupt" option on.

**To Reproduce:**
//Do not auto interrupt is on
`SysMessage('1')`
`Pause(1000)`
`SysMessage('2')`
`Pause(1000)`

**Comment by d0tsd0tsd0ts** [comment]
Ty Draggg85, i will try to reproduce to track problem

**Comment by Draggg85** [comment]
It seems only if you have more than 20 macros and names of some macros have special character like":",then you can use the macro above to reproduce the problem.

**Comment by d0tsd0tsd0ts** [comment]
I used the macro but it's working properly, i wont see the problem as i reported...

My report is happening when u hold button, Macro is getting delay, not working in row...

I've noticed that it ish happening with objects, not spells..
