### ISSUE TITLE
Queued targets last indefinitely instead of timing out after a few seconds as with Steam.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#145]
- ClassicUO Version: 0.1.7.58
- ClassicAssist Version: 0.3.236.0

**Comment by d0tsd0tsd0ts** [comment]
Reetus: i'm muting this server and disappearing into the wilderness

**Comment by Reetus** [comment]
Never heard of such a thing...

I've added an option in 0.3.259.295 to set a timeout...

![image](https://user-images.githubusercontent.com/6239195/111864678-68706800-899d-11eb-9588-1cc008343801.png)

I've only done basic testing, so if you can verify it works as expected...

**Comment by Timorio** [comment]
It's functioning mechanically, but it could use a system message saying that the queued target has timed out.  It's also giving an "Invalid or unknown object id" error when bringing up a targeting cursor after the timeout.

**Comment by Timorio** [comment]
Scratch that.  Today, it's flat out not queuing targets.
