### ISSUE TITLE
When using intellisense, display the arguments the highlighted method will accept, and the return-value type.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#147]
ClassicAssist version: 0.3.236.0

It'd be most useful if the arguments took a plain-English form that represents the meaning of the argument (e.g., FindObject(obj, range, findlocation).  These can be displayed in a small box beneath the currently highlighted item.

Displaying these as a mouse tooltip when mousing over an intellisense item may also be useful.

**Comment by Reetus** [comment]
Implemented in 0.3.288.315
