### ISSUE TITLE
Feature request: Containers Grid And Search

### ISSUE THREAD

**Issue by tsukasa696** [Reetus/ClassicAssist#152]
As title say Containers Grid And Search.

It will be cool if there any possibility to implement at least the container grid sys, 

Container Grid:  the possibility to turn any container in to a grid, it's more order way and easy to find items.
![bpgrid](https://user-images.githubusercontent.com/27456027/112726380-610d0980-8f1d-11eb-9f09-c2dca66b458a.jpg)

The search basically allow to search in the backpack or body by any item property (name, bonus, etc), after click the gump button it activate search mode:
![bpgridsearch](https://user-images.githubusercontent.com/27456027/112726422-aa5d5900-8f1d-11eb-8074-bf539ed25aa8.jpg)
![bpgridsearchres](https://user-images.githubusercontent.com/27456027/112726424-adf0e000-8f1d-11eb-8d47-da2f87e22346.jpg)

Note: this it's not my idea, i use this system in OrionUO.

**Comment by Reetus** [comment]
See 'Grid Container Viewer' in hotkeys, you should direct your request to ClassicUO, creating gumps with reflection is problematic.
