### ISSUE TITLE
import random

### ISSUE THREAD

**Issue by DefoeChan** [Reetus/ClassicAssist#162]
I want to use the random module to generate a random integer. 
```
import random
x = random.randrange(1400, 1450)
```
Can you include this module in ClassicAssist, please?

**Comment by d0tsd0tsd0ts** [comment]
u can use it

`
from System import Random
random = Random().Next(3)
print(random)`

**Comment by d0tsd0tsd0ts** [comment]
if u want to use python module, u need to include ironpython module on module folder

**Comment by DefoeChan** [comment]
Worked for me, thanks!
Is this C#?

**Comment by d0tsd0tsd0ts** [comment]
First, yea..
