### ISSUE TITLE
Can't move gold coins from backpack to bank.

### ISSUE THREAD

**Issue by DefoeChan** [Reetus/ClassicAssist#17]
Hi, I am trying to set up a marco to move gold from backpack to bank. Can't figure what's wrong with my line.
`MoveType(0xeed, "backpack", "bank")`
The program is expecting int and not liking strings. Is this intentional or is there a workaround?

**Comment by Reetus** [comment]
I've updated the method signature to allow for aliases to be specified...

This is fixed in version [0.2.18.113](https://github.com/Reetus/ClassicAssist/releases/tag/0.2.18.113)

Thankyou for your report...
