### ISSUE TITLE
ClassicAssist freezes up when stopping macros.

### ISSUE THREAD

**Issue by Grok0** [Reetus/ClassicAssist#171]
**Information**

- ClassicUO Version: 0.1.8.41
- ClassicAssist Version: 0.4.331
- Client Version: 7.0.90.16
- Shard: Any

**Describe the bug**

Almost every time I stop a macro, Classic Assist freezes up and I can't close the client or anything. I have to end the entire ClassicUO process to get it to shut down and restart. That means almost every time I stop a macro, I have to relog which gets me killed often.

I've tried to run ClassicAssist as admin to see if maybe that would help - it didn't. I'm kinda out of ideas at this point.

**Comment by Reetus** [comment]
If you have a looping macro with no delay, such as...

```py
if FindType(0xfff):
    #do something
```

Either add a Pause outside of the if, such as...

```py
if FindType(0xfff):
    #do something
Pause(500)
```

or, wrap the whole thing in a while True, such as...

```py
    while True:
        if FindType(0xfff):
            #do something
```

Advise if this fixes/doesn't fix your issues

**Comment by Grok0** [comment]
I always make sure to have pauses or conditional statements to avoid those issues. This one is specifically while pressing "stop" on the macro. Funnily enough, if I use a keybind to stop the macro, there's no crashes.

**Comment by Reetus** [comment]
Should be resolved in latest version
