### ISSUE TITLE
Follow

### ISSUE THREAD

**Issue by DefoeChan** [Reetus/ClassicAssist#173]
Please add a follow command that will act the same as Alt + Left Click.

Pathfind misses fast-moving targets by a few steps, and it causes crash when I use Pathfind loop too frequent.

**Comment by d0tsd0tsd0ts** [comment]
Pathfind is working normally here...

Include Pause() after command... 

Show ur code and what u are wanting

**Comment by d0tsd0tsd0ts** [comment]
I dont have this problem. Pathfind accepts x y z, not alias...

**Comment by DefoeChan** [comment]
Pathfind does accept alias. It will take the xyz of the alias and pathfind there.
The problem with pathfind is that when I charge towards a mob, the mob might also be moving towards me, causing me to overshot by a few steps and shoving into it.
When in a PVP situation, pathfind loop with a pause is way too slow for my script to chase human players.

The in-game built-in follow function is basically a forever-updating pathfind loop, which IMO is way more effective when chasing a moving target.

**Comment by Reetus** [comment]
See Follow and Following... https://github.com/Reetus/ClassicAssist/wiki/Movement

**Comment by ghzatomic** [comment]
Hello, im trying to use the Follow('enemy'), but no success .. show me an error of null reference, someone can help me ?
