### ISSUE TITLE
Autoloot Agent General types or wildcards

### ISSUE THREAD

**Issue by BadManiac** [Reetus/ClassicAssist#185]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the autoloot agent to loot ANY item with the word "Artifact" in the properties. Regardless if Lesser, Major, Greater or Legendary. And regardless of item type.

**Describe the solution you'd like**
An option to add custom items to the autoloot agent not by targeting an item, but simply a wildcard, and being able to set properties on that for the  agent to look at.

**Describe alternatives you've considered**
Not sure any alternative exists for ClassicUO, for "regular UO" client this can be achieved by any number of scripts and macros.

**Additional context**
N/A

**Comment by Reetus** [comment]
Any item can be done by right clicking on insert

![image](https://user-images.githubusercontent.com/6239195/118820676-b0016a80-b8e0-11eb-9b52-ec4542c4d3d0.png)

For now you will need to add entries for lesser/greater/etc

**Comment by Reetus** [comment]
If the property you're looking for isn't there...

![image](https://user-images.githubusercontent.com/6239195/118823224-02438b00-b8e3-11eb-99ee-34edb66b3d31.png)

**Comment by BadManiac** [comment]
Fantastic, just tested it and it works, thank you!
