### ISSUE TITLE
Windows Apps Scale

### ISSUE THREAD

**Issue by PoodyCZ** [Reetus/ClassicAssist#188]
A friend found a weird bug regarding CA
He has scale set to 125% on his monitor (in windows settings System > Display)
A CUO client without CA scales, but CUO client with CA does not scale, the CA window scales though
Razor doesnt seem to have any effect, so it should be CA

Set scaling in Windows to 125%
Launch CUO without CA
Launch CUO with CA
Compare window size

**Expected behavior**
CUO window should scale

**Screenshots**
https://cdn.discordapp.com/attachments/785605379580493854/845707004164309012/resolution.jpg

**Comment by Reetus** [comment]
![unknown-3](https://user-images.githubusercontent.com/6239195/119243405-9ab26780-bb90-11eb-97c2-55e9f0b6ce4c.png)

I tried to find a way to fix it programmatically but haven't been able to
