### ISSUE TITLE
Memory leak & Crash

### ISSUE THREAD

**Issue by DefoeChan** [Reetus/ClassicAssist#19]
ClassicUO.exe ate up to 10GB RAM and crashes the game.
I don't see errors on the console. It happens when there are a number of corpses nearby, say 8+, but I have had crashes with only 3 nearby.

I will test different versions, which may give a clue.
0.2.18.113 Good
0.2.18.114 To be tested
0.2.19.115 To be tested
0.2.19.120 To be tested
0.2.20.121 To be tested
0.2.23.122 Memory leak & Crash
0.2.27.123 Memory leak & Crash

**Comment by DefoeChan** [comment]
0.2.18.113 Good
0.2.18.114 Test skipped
0.2.19.115 Test skipped
0.2.19.120 Test skipped
0.2.20.121 Good
0.2.23.122 Memory leak & Crash
0.2.27.123 Memory leak & Crash

I guess it's a bug introduced in 0.2.23.122.

**Comment by Reetus** [comment]
I haven't experienced it, so it's environmental, if you can find a way to reproduce it, it would help.
