### ISSUE TITLE
Is there a target non-friendly option just like razor? If not, may I know how to script it?

### ISSUE THREAD

**Issue by TraderJoe329** [Reetus/ClassicAssist#191]
**Is your feature request related to a problem? Please describe.**
If I'm not missing such function, then I'm annoyed to use 3 diff hotkeys to target closest gray, murderer and enemy while razor has non-friendly type which allows targeting the closest attackable mobile (not innocent/friend).

**Describe the solution you'd like**
Have target closest non-friendly functions for mobile, humanoid. 

**Describe alternatives you've considered**
Can share how to script it?

**Additional context**

**Comment by PlueRyvius** [comment]
GetEnemy(["Murderer, Criminal", "Enemy", "Gray"],  "Any", "Closest")

**Comment by TraderJoe329** [comment]
Thank you
