### ISSUE TITLE
Random socket error

### ISSUE THREAD

**Issue by CalebFenton** [Reetus/ClassicAssist#192]
**Information**
- ClassicUO Version: 0.1.8.0
- ClassicAssist Version: 0.4.345

There's a socket error 10-60 seconds after selecting character. Here are the relevant logs from a debug build of ClassicUO:

```
11:18:21 |  Info    | Connected!
11:18:22 |  Error   | Attempt to write into a dead socket
11:18:23 |  Error   | Attempt to write into a dead socket
11:18:24 |  Trace   | Disconnected [login socket]
11:18:29 |  Info    | Razor ACK sent
```

**To Reproduce**

Select character and wait 10-60 seconds. You can stand still in a low pop area. Doesn't happen if ClassicAssist is removed from plugins list and only ClassicUO is running.

**Comment by Reetus** [comment]
What shard?
