### ISSUE TITLE
how to make macro ??  if dismout  debuff end mount my ride pet

### ISSUE THREAD

**Issue by hwangsew** [Reetus/ClassicAssist#194]
how to make macro ??  if dismout  debuff end mount my ride pet??

i want to make macro

if dismount debuff   :
 msg("all follow me")
 mounted  mount my ride pet

or never dismount macro 

please solve it~

**Comment by Batt11** [comment]
Not sure what you are saying, but if you want to do a check if your mounted, and say All follow me if you are dismounted

if not Mounted("self"): 
	Msg("All follow me")

If you are looking to check if your mounted and then dismount and say all follow me, or just say all follow me if you are already dismounted:

if Mounted("self"):
	ToggleMounted()
	Msg("All follow me")
else:
	Msg("All follow me")

**Comment by hwangsew** [comment]
thank you 

i solve it
if not Mounted("self") and not BuffExists("Dismount Prevention") :
	Msg("All follow me")
	ToggleMounted()	
	Pause(300)
