### ISSUE TITLE
Feature Request: Target water / tile for Fishing

### ISSUE THREAD

**Issue by DefoeChan** [Reetus/ClassicAssist#20]
I can't figure out how to target water tile.
`TargetTileRelative("self", 3, False)` don't seems to work.

**Comment by Reetus** [comment]
![ClassicAssist-2020-4-1-19-19-58](https://user-images.githubusercontent.com/6239195/78131556-da2e6980-744d-11ea-9792-9be7af820d16.gif)

It's working for me both from a boat and on land, can you provide more information, shard/location and I will investigate...

**Comment by DefoeChan** [comment]
Just tried again on boat.
Works on a boat. Not on the shore.

**Comment by DefoeChan** [comment]
I'm on UO Forever, Eiffel Island. Tried other land, doesn't work as well.

**Comment by Reetus** [comment]
Can you try with latest version and report back if it's still a problem...
