### ISSUE TITLE
UseObject does not trigger target

### ISSUE THREAD

**Issue by skjarl** [Reetus/ClassicAssist#202]
**Information**
- ClassicUO Version: 0.1.8.135
- ClassicAssist Version: 0.4.346
- Client Version: ?
- Shard: UO Evolution

**Describe the bug**
I am using UseObject on cotton plants in Occlo/New Haven, but no cotton is being generated.

**To Reproduce**
1. Stand near a cotton plant
2. Run this code:

`FindType(0xc52)`
`Pathfind("found")`  
`UseObject("found")`

3. You'll walk to the plant and nothing happens.

**Expected behavior**
Expectation is that you walk to the plant, double click it, and a piece of cotton appears on the ground. The scavenger would then pick it up and you could move on.  This works if you manually walk up and double click the plant.

**Screenshots**
![image](https://user-images.githubusercontent.com/10904006/126073774-fd4ebd39-cbd6-469c-bcc8-fd470d902277.png)

**Comment by Reetus** [comment]
Pathfind doesn't block, so you'll need to ensure you're close enough...

```py
distance = 18

if FindType(0xc51, distance) or FindType(0xc52, distance) or FindType(0xc54, distance):
	Pathfind('found')
	while Distance('found') > 1:
		Pause(50)
	UseObject('found')
Pause(2000)
```

![image](https://user-images.githubusercontent.com/6239195/130304806-5c7ecd54-4fac-4665-9aaf-38eb468572ca.png)
