### ISSUE TITLE
Buff problem

### ISSUE THREAD

**Issue by chiconanni** [Reetus/ClassicAssist#209]
**Information**
- ClassicUO Version: 0.1.9.67
- ClassicAssist Version: 0.4.357
- Client Version: 7.0.90.16
- Shard: Heritage

**Describe the bug**
Seems like assistant is ignoring Buffs. As you can see at the video, i have this simple macro that drinks agility potion when agility buff is not present. It was working before on 0.4.356, now he keeps drinking pots ignoring the buff. 
**To Reproduce**
1. Go to Macros and make new macro as you can see on video and hit play

**Expected behavior**
That assistant respect if the right buff is on buff bar.

**Screenshots**
There is no screenshot, but have this video:
https://www.youtube.com/watch?v=k3tcy6OHfXM&ab_channel=FranciscoNanni

**Comment by d0tsd0tsd0ts** [comment]
Put mouse on buff and check if name is right...

**Comment by chiconanni** [comment]
hello.. ty for your reply... as ive said, it was working pretty good before the mentioned patch. It was suppose to work on the latest version unless you guys have changed the name of the buff. I do use that macro for about 8 months now... so..  why it works if i rollback some assistant versions?

**Comment by chiconanni** [comment]
from BuffIcons.json

```
{
    "ID": 1045,
    "Name": "Agility"
  }

**Comment by Reetus** [comment]
[https://www.youtube.com/watch?v=LkOtryNs0wU](url)

I can't reproduce this with the same variables (versions/shard/etc)

Can you open debug menu / bufficon and see if it is displaying Agility as per my video?

**Comment by chiconanni** [comment]
goingo to record now

**Comment by chiconanni** [comment]
ok, here it is... please notice that even when i stop the macro, he keeps drinking...

https://www.youtube.com/watch?v=o6vLC2d4CgY&ab_channel=FranciscoNanni

**Comment by chiconanni** [comment]
![image](https://user-images.githubusercontent.com/69136836/132069812-2ce372ea-50e8-44c4-9f7b-7ad4ac83e97e.png)
Insert a pause and set the macro to loop...

**Comment by chiconanni** [comment]
if do a macro, equal to your video, and dont tip the loop, works preety same as your video!

**Comment by Reetus** [comment]
Add a Pause after UseType long enough that the bufficon appears before the Pause ends
