### ISSUE TITLE
Profile/Character name in windows head bar

### ISSUE THREAD

**Issue by MatcherUltra** [Reetus/ClassicAssist#21]
Is it possible to adjust the code to show the character name (or, alternatively, the profile name) in the ClassicAssist UI headbar? I usually play with three accounts simultaneously and it's been a pain to find the proper ClassicAssist window when switching characters. Thanks and congrats for the project!

**Comment by Reetus** [comment]
Implemented in [0.2.72.133](https://github.com/Reetus/ClassicAssist/releases/tag/0.2.72.133)...

Character name will show in window title once available with an option to also show profile name...

![image](https://user-images.githubusercontent.com/6239195/81472212-1f9e3d80-9229-11ea-9e44-9a1658d6d563.png)

Thank you for your report...

**Comment by MatcherUltra** [comment]
Hey, Reetus.

Thank you for your effort in developing this awesome Assistant. I only wish I knew how to code in order to help you... 

In case I notice another opportunity for improvement I'll let you know.

Regards!

Enviado do meu iPhone
