### ISSUE TITLE
Some messages in the Journal are not detected by ClassicAssist

### ISSUE THREAD

**Issue by Pebin** [Reetus/ClassicAssist#215]
**Information**
- ClassicUO Version: 0.1.8.22
- ClassicAssist Version: 0.4.364
- Client Version: ?
- Shard: Andaria

**Describe the bug**
Some messages in the Journal are not detected by ClassicAssist. For example, a message that I am trying to move items that are in a bag that is out of reach.

**To Reproduce**

I wrote a simple script that just prints everything that appears in the journal but the behavior is the same with the built-in InJournal and WaitForJournal macro as well. I was just looking for some MVP while investigating this.
```python
from Assistant import Engine

ClearJournal()
while True:
	for entry in Engine.Journal.GetBuffer():
		print(entry.Text)
	ClearJournal()
	Pause(1000)
```

This almost always works but some messages never appear there. For example:
1. I want to move something that's in a bag that is out of reach (close distance, the bag is already opened but I am standing behind a tree)
2. I get a message "You can't pick it up." (translated from the Czech version that's used on that shard) but this is never printed.

On the other hand, when I try to open the bag which is behind the tree I get a message "You can't reach that" (again translated) and this is properly printed. (tbh almost everything is properly printed)

The reason why I want this is to be able to detect when I fail to move something with MoveType because it's behind a wall.

I also noticed that when the message about increased skill appears, it's not "printed" by that script.

**Expected behavior**
To be able to read all the messages which appear there

Here is a screenshot, you can see that the last "Nemuzes to zvednout" message is not printed again as are the previous messages
![image](https://user-images.githubusercontent.com/8281747/133930497-ca463832-5f54-41cc-ab3b-8d1c419bbb37.png)

**Comment by phlm7th** [comment]
When I use Pathfind() to where can't reach, 'System: Maximum distance exceeded.' is displayed in journal. But InJournal() can't detect this too.

**Comment by d0tsd0tsd0ts** [comment]
@Pebin 

- [x] Done

**Comment by Pebin** [comment]
I finally found some time to play Ultima ❤️ again but this fix doesn't seem to work 😢  
I am testing it with 0.4.404. The reproduction steps are exactly the same as before

I also tried InJournal and WaitForJournal macros directly with no luck 
@d0tsd0tsd0ts
