### ISSUE TITLE
Possible features

### ISSUE THREAD

**Issue by Apellamen** [Reetus/ClassicAssist#22]
1-Paint commands (for serial/aliases)
**Paint(lasttarget, '2974')**
**ClearPaint(lasttarget)**
![snap_screen_20200522200958](https://user-images.githubusercontent.com/47136830/82663205-305ba400-9c6a-11ea-822c-3128950a46d6.png)

2-Autoloot Agent: An option "Loot Humanoids ON/OFF" in the autoloot agent (basically, something that ignore bones and Humanoids)

3-Autoloot Agent: An option "Loot Innocent corpse ON/OFF" in the autoloot agent. Some shards send corpses notoriety packets (or it should work on journal check? or both?)

4-A command for pop the statusbar at X, Y cordinates on the screen (for serial/aliases)
**StatusBar(lasttarget, 1185, 50)**

5-Dress Agent: An option for "Doubleclick for Equip"

**Comment by Reetus** [comment]
> 5-Dress Agent: An option for "Doubleclick for Equip"

What does this mean? you doubleclick an item in your backpack and it equips it?
