### ISSUE TITLE
Getting the graphic ID of something on the ground

### ISSUE THREAD

**Issue by Batt11** [Reetus/ClassicAssist#220]
I am developing a macro for just walking around and chopping trees. when I hit something unpassable, like a house, or water, I change direction and move another way. This seems to be working except I get caught up on one type of ground item. Some Brambles (GraphicID 0xd40) are passable and I walk over them, other Brambles (GraphicID 0xd3f) push me back when I try to walk over them. 

The system does not see this push back as unpassable, so my macro hangs while trying to walk over this object. I am trying to find a way to get the ID of the tile ahead of me and check if it is the 0xd3f ID and then change direction. So far, I have failed to acquire this Graphic ID other than using the object inspector. Is there any way for me to do this?

**Comment by KevinEady** [comment]
```py
from ClassicAssist.UO.Data import Statics

statics = Statics.GetStatics(int(Engine.Player.Map), x_coord, y_coord)
```

This `statics` will be a list of [`StaticItem`](https://github.com/Reetus/ClassicAssist/blob/master/ClassicAssist/UO/Data/StaticTile.cs#L3)s. You can check each one's `ID`.

Let me know if this helps.

**Comment by Batt11** [comment]
Thank you, I will have to research how to get the x and y of the tile ahead of me

**Comment by Batt11** [comment]
I got this working, with grabbing the  ID of the static if front of me, it works most of the time, but others, I still get hung up because the static it finds is grass I will continue to work on it.
