### ISSUE TITLE
Issue with closest enemy?

### ISSUE THREAD

**Issue by solracCH** [Reetus/ClassicAssist#23]
Hi

I've been playing around with ClassicAssist and loving it so far.

There seems to be quite an issue with getting targets using Macros like:

GetEnemy(['Gray'], 'Any', 'Closest'):

Often, a mob standing even right next to you will never be set as "enemy", the macro will get a mob somewhere almost offscreen if at all. 

Keep up the excellent work guys!

**Comment by thiagotigaz** [comment]
I can confirm targeting is a little off...

i have:
GetEnemy(['Innocent'], 'Humanoid', 'Previous')
and:
GetEnemy(['Innocent'], 'Humanoid', 'Next')

and 3 static players on screen, it doesn't go back and forth in the same order, it randomly switchs between the players even though they aren't even moving.

**Comment by Reetus** [comment]
> Hi
> 
> I've been playing around with ClassicAssist and loving it so far.
> 
> There seems to be quite an issue with getting targets using Macros like:
> 
> GetEnemy(['Gray'], 'Any', 'Closest'):
> 
> Often, a mob standing even right next to you will never be set as "enemy", the macro will get a mob somewhere almost offscreen if at all.
> 
> Keep up the excellent work guys!

If it attacks you then it is probably Criminal and not Gray, try with Criminal added and report back...

**Comment by Reetus** [comment]
> I can confirm targeting is a little off...
> 
> i have:
> GetEnemy(['Innocent'], 'Humanoid', 'Previous')
> and:
> GetEnemy(['Innocent'], 'Humanoid', 'Next')
> 
> and 3 static players on screen, it doesn't go back and forth in the same order, it randomly switchs between the players even though they aren't even moving.
> 
> It would be nice to have previous hotkeys available instead of having to code it, it would only require to save current before going to next and would also prevent this issue.

There is no previous currently, it's ignoring what you write and doing next.

**Comment by thiagotigaz** [comment]
> > I can confirm targeting is a little off...
> > i have:
> > GetEnemy(['Innocent'], 'Humanoid', 'Previous')
> > and:
> > GetEnemy(['Innocent'], 'Humanoid', 'Next')
> > and 3 static players on screen, it doesn't go back and forth in the same order, it randomly switchs between the players even though they aren't even moving.
> > It would be nice to have previous hotkeys available instead of having to code it, it would only require to save current before going to next and would also prevent this issue.
> 
> There is no previous currently, it's ignoring what you write and doing next.

any expectation on implementing it?

**Comment by solracCH** [comment]
> If it attacks you then it is probably Criminal and not Gray, try with Criminal added and report back...

U were actually right. If the target has targeted me its considered "criminal" and no longer "gray" which explains the behavior.

Thanks for the help. well appreciated
