### ISSUE TITLE
Tools for compilling

### ISSUE THREAD

**Issue by thiagotigaz** [Reetus/ClassicAssist#24]
What do I need to compile the code? I'm downloading visualstudio but not sure which to select during installation.

I want to do a few tests on TargetManager class. `Reverse` boolean should use `_ignoreList` instead of mobiles and if `_ignoreList` is empty we should populate with the reverse of the returned mobiles from the query you do above(except for the contains on ignoreList) and instead of adding to ignoreList you gonna remove from it so that it becomes available in case player does next.

**Comment by Reetus** [comment]
Visual Studio 2019 (Community is fine), the option in the installer is .NET Desktop Application Development (or similiar)
