### ISSUE TITLE
Screen Freeze

### ISSUE THREAD

**Issue by CraigsHere** [Reetus/ClassicAssist#241]
**Information**
- ClassicUO Version: 0.1.10.131
- ClassicAssist Version: 0.4.380
- Client Version: 7.0.91.15
- Shard: Dark Forest

**Describe the bug**
My screen freezes.  I'm still connected to the server but I'm unable to see myself do actions or see anyone else perform actions.
Sometimes when I freeze I get random gumps popping up like a book that automatically
turns pages as many as 67k times before it disconnects or a dye tub color picker and a 
handful of other gumps.  Neither a book or dye tub are present in game. I've ran Razor 
Enhanced as a plugin and after I freeze I am able to press undress in RE; because of the 
freeze I dont see it undress me but when I relog I am undressed.  Checking task manager, 
my program still responds according to windows and I still stay logged in to the game for 
long periods before a disconnect.  Periods being up to hours sometimes.
This incident is not isolated to my PC alone.  Many on Dark Forest Share this fate.
Installing older releases, running through launcher or as a CUO plugin all yield same results.
There are none of these issues if I use the same CUO & Razor Enhanced directories without CA.

**To Reproduce**
This is easily reproduced simply by relogging.  It's happened when running macros and normal gameplay.
It's happened standing still in town or a house with nothing running.

**Screenshots**

![ca cuo freeze](https://user-images.githubusercontent.com/97825814/149653126-e4664ded-b98f-41d6-8927-ed675ee2fa5b.jpg)

**Comment by gonculator** [comment]
I've had the exact same issue on the exact same build. Updated (forget to which build) and problem went away. CA updated recently to 0.4.410 and started doing it again. It happens for no reason, not running scripts, just standing in the same spot or while actively playing (no rhyme or reason).

**Comment by alrickUA** [comment]
Also experiencing same issues - sometimes it's only one freeze a day, and sometimes it's three freezes within an hour. 

One of the freezes had a targeting cursor appear asking "Click on the player whom you wish to remove as a co-owner". Even though I was in bank area and nowhere near any homes. I don't even own a home on that shard.

Could this be some stray packet sent by the shard or the ClassicAssist? I've been running CUO in debug mode with network logging trying to catch it, will report when I catch the freeze.

Is there any way to turn on logging or debug mode for ClassicAssist? Should I just run debug build via Visual Studio and see where it stalls?

**Comment by alrickUA** [comment]
I should add that I got exactly same freeze when using razor and so did another user on same shard. 
My guess is that freezes are more rare on Razor, so I try to catch it using CUO with CA. Yesterday played for 4 hours and it didn't freeze while in a debugging session with VS.

**Comment by Reetus** [comment]
Issue is with ClassicUO, compile latest main branch of ClassicUO and report issues to this discord... https://discord.com/channels/458277173208547350/1080335372963283035
