### ISSUE TITLE
uosteam

### ISSUE THREAD

**Issue by rodrigotbo** [Reetus/ClassicAssist#27]
is there a way to convert uosteam scripts to classicAssist? i'm trying to make an auto bandage script

**Comment by Reetus** [comment]
There isn't any way to automatically convert from uosteam, you will need to convert manually by reading a python guide and the [Macro Commands](https://github.com/Reetus/ClassicAssist/wiki/Macro-Commands)

**Comment by rodrigotbo** [comment]
Got it, thanks.

str = Str()
if Hits("self") < str:
	BandageSelf()

It was that simples to make an auto bandage script. This is really awesome, great work. Regards from Brazil.
