### ISSUE TITLE
Loot sorting

### ISSUE THREAD

**Issue by solracCH** [Reetus/ClassicAssist#28]
Hey 

Found another possible issue. I was trying to re-write a chest loot macro from UOsteam to classicAssist. It would loop through items in chest, use item id, and only keep vanq/invul items. In steam i used to check the journal for the keywords. I tried the same with classicassist and it wasn't working.

I have some basic c# skills from a former life and attached a debugger. Seems that the Journal entries dont contain the result of item identification, even though they're visible in the journal. 

As a fall back, i looked at the Property() command. Figured out i could detect vanquishing by using "damage increase 9%" for vanq. However, there's nothing pointing to invul.

Just thought i'd report it, in case you'd want to have a loot at it.

Cheers

**Comment by Reetus** [comment]
I've pushed an update to send a line from the DisplayEquipmentInfo packet to the journal, if you want it formatted like in game, feel free to fork the code and do so yourself...

I populate Item.Properties with the information from the DisplayEquipmentInfo packet for the FindWand commands, you should be able to search Item.Properties for the mods you are after (Once you have ClickObject'd on the item)

1038020 = Vanquishing
etc

![image](https://user-images.githubusercontent.com/6239195/84134451-2d8aec80-aa7b-11ea-9e0b-60170eb2ae67.png)
