### ISSUE TITLE
Features/Ideas/Bugs

### ISSUE THREAD

**Issue by Morph247** [Reetus/ClassicAssist#29]
Hi Reetus

I've fallen in love with CUO but it was Classic Assist that made it actually usable for me. You're doing an amazing job! I've been using Classic Assist for about a month as my daily driver and i thought i'd share some findings and ideas you may or may not want to look at, but it's all i can provide to try to make classicassist better.

**Scavenger**
For whatever reason, i didnt it to work at all. No matter what i do or try, it just ignores items on the ground.

**Provocation**
tried to use Classic Assist to macro provocation. Couldn't get it to work. Basically, when the skill prompts you for the 2nd mob, it just does nothing.

**Counters / Counter warnings**
The display of the counter below set treshold is displayed in the same color als all other messages. It's easy to not see it. It would be nice if a color could be set or at least it was a different color, like you did to autoloot recently. Also, it would be helpful, if it would report that you're under the warning treshold you set and not once when u actually go below.

**Autoloot**
Autoloot is a great click-saving feature. And while it works fine on a single mob, it seems to struggle as soon as you walk over multiple mobs. Feels like its getting confused if it should be looting or opening new corpses. And if it fails to grab the item for whatever reason, it doesnt try again unless you manually re-open the corpse, while uosteam would be looking trying to loot it. Like, if for whatever reason a corpse opened behind a wall (out of sight), on steam you could walk around the corner and it would grab it, classic assist wont react. 

Thats all i can think for now. Dont take the feedback as criticism, i love your work! 

morph

**Comment by Reetus** [comment]
Provoke issue is fixed in the latest build

**Comment by Morph247** [comment]
Tested it, works like a charm! Thanks for the good work

**Comment by Reetus** [comment]
Scaenger previously wouldn't try to pick up items placed next to you, only as you ran past them, I've changed it to check new items added within the range.

It still maintains an ingore list because I didn't want like UOS where it's impossible to dispose of an item that is in your scavenger list.

I've changed the colour of the counter warning message and it will show if you're at the warning amount.

If you can test the changes and report back if any problems.

**Comment by Reetus** [comment]
![image](https://user-images.githubusercontent.com/6239195/89656479-37f02800-d8fe-11ea-9f07-214f2098705c.png)

Try this option alongside 'Use object queue' option and open a new issue if you still have issues.
