### ISSUE TITLE
How should "Hotkeys" be used?

### ISSUE THREAD

**Issue by murazi** [Reetus/ClassicAssist#297]
**Information**
- ClassicUO Version: 0.1.10
- ClassicAssist Version: 0.4.404
- Client Version:7.0.7.1
- Shard:Legacy

```
Hotkeys(on)

Hotkeys(onff):on

Hotkeys(Enble)

Hotkeys():on
```

Checked [WIKI](https://github.com/Reetus/ClassicAssist/wiki/Main#Hotkeys), it seems to be wrong

**Comment by joma-s** [comment]
You don't seem to be using it correctly.

It's either only `Hotkeys()` to toggle between on and off, `Hotkeys("on")` or `Hotkeys("off")`
Note "on" or "off" go between quotes as they're a string in python, not a variable. 

From my tests, if you pass anything else inside Hotkeys() like Hotkeys("ok") it'll just toggle as well.

**Comment by murazi** [comment]
> 您似乎没有正确使用它。
> 
> 它要么只是`Hotkeys()`在开和关之间切换，`Hotkeys("on")`要么`Hotkeys("off")` 注意“开”或“关”在引号之间，因为它们是 python 中的字符串，而不是变量。
> 
> 根据我的测试，如果你在 Hotkeys() 中传递任何其他东西，比如 Hotkeys("ok")，它也会切换。

okey，thx~
