### ISSUE TITLE
Feature request: last target command

### ISSUE THREAD

**Issue by gzozulin** [Reetus/ClassicAssist#32]
A valuable link in different scenarios.
Once again, if it is already possible to achieve that somehow, please show a snippet.

**Comment by Reetus** [comment]
Target('last') ?

**Comment by gzozulin** [comment]
'last' is a predefined alias?

**Comment by Reetus** [comment]
yes

**Comment by gzozulin** [comment]
ok, I see, thanks!

**Comment by gzozulin** [comment]
@Reetus doesn't work: unknown alias 'last'. Maybe I am missing something?
Here is an example of usage:
`if not (FindAlias("axe")):
	PromptAlias("axe")

UseObject("axe")
WaitForTarget(5000)

while True:
	UseObject("axe")
	ClearJournal()
	Target("last")

	while not InJournal("you chop", "system"):
		Pause(250)

	if InJournal("done", "system"):
		SysMessage("<<<<<<<<<< DONE >>>>>>>>>>>")
		break`

**Comment by Reetus** [comment]
Is your target an item/mobile, or a static/land target?

last target doesn't work on static/land targets, in any assistant

**Comment by gzozulin** [comment]
it was a tree :(
btw, on Renaissance I cannot receive info about a tree with object inspector - it is the same problem?
I also cannot target trees with

`TargetTileOffset(0, 1, 0)`

Maybe you can suggest something? Lumberjacking is boring..

**Comment by Reetus** [comment]
Try in the latest update...

**Comment by gzozulin** [comment]
Hello, @Reetus 
Tried on the latest version (*.196)
Unfortunately, I still cannot target tree tiles. Object inspector also do not work on trees.

Simple snippet:
UseObject(0x491cecd8) // < Axe
Pause(250)
TargetXYZ(1958, 2845, 0) // << I tried different options here: Target("last"), TargetTileOffset, etc..

**Comment by Reetus** [comment]
![ClassicAssist-2020-7-2-11-17-47](https://user-images.githubusercontent.com/6239195/86313030-b4844c80-bc56-11ea-89de-5c58c2533184.gif)

Object inspector should work on trees

Try it with .198 just released

If it doesn't work, let me know what shard and where you are trying to chop.

**Comment by gzozulin** [comment]
Unfortunately, the same results...
I am playing on Renaissance.
If you need any assistance reproducing - just let me know.

Basic steps are:
1) Go to private Macroses
2) Click on the Object Inspector
3) Have a target in UO
4) Target at the root of the tree
5) Target disappears, no Object Inspector window

**Comment by Reetus** [comment]
Ok, I didn't update object inspector from macros, try the hotkey

I'm not strong enough to hold an axe but TargetTileOffset with a dagger works with the Renaissance client

![image](https://user-images.githubusercontent.com/6239195/86316120-8e62aa80-bc5e-11ea-8383-2b210dd4fd23.png)

**Comment by gzozulin** [comment]
Success! With hotkey, it works. Also, TargetXYZ works as well.

**Comment by Reetus** [comment]
The change was causing a problem with other people targeting the ground, use TargetTileOffsetResource
