### ISSUE TITLE
option to pass values to PlayMacro()

### ISSUE THREAD

**Issue by qkdefus** [Reetus/ClassicAssist#328]
i.e
PlayMacro("macroname", "targetSerial1", "targetSerial2")

**Comment by Reetus** [comment]
Would your suggestion be like...

Played Macro:
![image](https://user-images.githubusercontent.com/6239195/214745687-40ce7e94-a8ae-4ad8-a77c-454c6acb2eaa.png)
Playing Macro:
![image](https://user-images.githubusercontent.com/6239195/214745727-8232bafa-974d-496d-895a-dce540a84be2.png)

or

Played Macro:
![image](https://user-images.githubusercontent.com/6239195/214745780-673c90a3-8aa8-47b3-bf11-e00b5b10f85a.png)
Playing Macro:
![image](https://user-images.githubusercontent.com/6239195/214745945-35f76a95-7233-4a19-a058-2de8997f173f.png)

Thinking option 2 for simplicity?

**Comment by qkdefus** [comment]
Option 2 looks great 👍

________________________________

**Comment by Reetus** [comment]
Options 2 is in 0.4.410 https://github.com/Reetus/ClassicAssist/releases/tag/0.4.410
