### ISSUE TITLE
Usable Skill not working

### ISSUE THREAD

**Issue by xeretic** [Reetus/ClassicAssist#33]
Hi, I'm playing on a shard where the lockpicking skill is executable. Lockpicking ist used to remove Traps. The problem is, i cant use the skill in my macro with UseSkill("Lockpicking"). If i do it, nothing happend, no Error, nothing. Probably because normaly the skill isnt useable?! Is it possible to make the skill executable in scripts? Thank you for help and great work, love your classicassist.

**Comment by Reetus** [comment]
Is your skills.mul modified to make it invokable?

**Comment by xeretic** [comment]
I asked the server owner for the information about the skills.mul. Yes i can invoke it from the Skill Gump ingame. Before i switched to classicuo, i used Steamuo. It was possible with useskill 'lockpicking' there to invoke it with a Script. Dont know if it is important...

**Comment by Reetus** [comment]
It should work if your skills.mul says it's invokable, can you upload your skills.mul somewhere that I can download?

**Comment by xeretic** [comment]
https://workupload.com/file/W8UKT5yVErJ

Its translated to german (lockpicking = schloesserknacken)

**Comment by Reetus** [comment]
Can I get the skills.idx too?

**Comment by xeretic** [comment]
Sure: https://workupload.com/file/EckjmdFkKrw

**Comment by Reetus** [comment]
Should be resolved in the latest update... you will need to do...
```py
UseSkill("Schloesserknacken")
```

**Comment by xeretic** [comment]
Thank you <3
