### ISSUE TITLE
Cast() macro leaves WaitingForTarget = True

### ISSUE THREAD

**Issue by Yubari** [Reetus/ClassicAssist#336]
**Information**
- ClassicUO Version: 0.1.11.39
- ClassicAssist Version: 0.4.407
- Client Version: 7.0.90.16.
- Shard: Inceptum (uogames.org)

**Describe the bug**
Cast() macro leaves WaitingForTarget = True, which breaks most of old UOSteam macroes and leads to boilerplate and non-effective code.

**To Reproduce**
1) Write simple macro: 
```
if WaitingForTarget():
    print("WaitingForTarget")
```

2) Check Loop, Run in background and launch it

3) Second macro:
```
Cast("Flame Strike")
```

4) Interrupt second macro from another client (optional, even without interruption next step always occurs)

5) First macro will print "WaitingForTarget" repeatedly even if cast was interrupted

**Expected behavior**
On UOSteam instead such situation was automatically handled, so the same macro won't spam "WaitingForTarget" in journal. Seems like UOS handling spell interruption internally. 

The summary: casting a spell with Cast() command sets Engine.WaitingForTarget to true and doesn't switch them back ever.
it can be avoided in macroes with calling WaitForTargetorFizzle(), but it is thread blocking, which forces us to wrap every Cast() in separate macro with further blocking it with WaitForTargetorFizzle(), which sets WaitingForTarget back, but this is very boilerplate solution.

**Comment by d0tsd0tsd0ts** [comment]
Waitingfortarget's steam works to know when target is success on manage cast or auto target... 

This behavior is not same on CA...

**Comment by Reetus** [comment]
Thank you for your report...

In an upcoming release, Cast(spell) will set WaitingForTarget = false after the spell timeout, additionally, if using fizzle detection, it will also clear the flag if fizzled etc...

Run a background macro with the following...

```py
if WaitingForTarget():
    print True
```

Run a foreground macro...

```py
Cast('Flame Strike')
InterruptSpell()
```

Without fizzle detection, if prints True until the spell timeout...

![image](https://github.com/Reetus/ClassicAssist/assets/6239195/6ff8e90e-1e16-4838-8f79-bf1fd8088436)

With fizzle detection if stops printing True when the spell is interrupted...

![image](https://github.com/Reetus/ClassicAssist/assets/6239195/6f06e66b-a9cd-4eaa-9cd7-66c625fcb20b)
