### ISSUE TITLE
hotkeys -> skills -> create macro button, not working

### ISSUE THREAD

**Issue by qkdefus** [Reetus/ClassicAssist#339]
if i create a macro button for any skill and click it, it says macro not found

**Comment by Reetus** [comment]
CUO Version?

**Comment by qkdefus** [comment]
Latest 👍

**Comment by Reetus** [comment]
Latest as in 0.1.11.58 from CUO Launcher?

It's working for me...

![ClassicAssist-2023-2-23-17-54-3](https://user-images.githubusercontent.com/6239195/220887119-acc6b3c0-227f-4a3b-bef2-2fc53840294e.gif)

Special/non alphanumetic characters in the macro name?

**Comment by qkdefus** [comment]
The skills tab

**Comment by qkdefus** [comment]
sorry for late reply, 12h work days 

![ClassicAssist-2023-2-24-21-47-20](https://user-images.githubusercontent.com/4680848/221288643-66cbef9b-d746-4d5e-a7a5-043251818b6f.gif)
