### ISSUE TITLE
FindLayer("Slot", serial) not working

### ISSUE THREAD

**Issue by xeretic** [Reetus/ClassicAssist#34]
Hi, 
FindLayer is not working. Example: 

FindLayer("OneHanded",  0x40152502)

If the Weapon is equiped he returns: Cannot find item.... 

On the otherhand EquipItem(0x40152502, "OneHanded") is working.... 

So if i use this Macro:
EquipItem(0x40152502, "OneHanded")
Pause(1000)
FindLayer("OneHanded",  0x40152502)

It returns Cannot find item....

**Comment by Reetus** [comment]
The second parameter to FindLayer is the mobile to check, not an item...

If ommited it will use the current player.

The use case is...

```py
if not FindLayer('OneHanded'):
    EquipItem(0x40152502, "OneHanded")
```

**Comment by xeretic** [comment]
Oh ok thank you. So ist there another Option to check which weapon is a equipped? If not i will go another way and Check which weapon is not equipped, by checking a bag for the weapon. If its in the bag, its not equipped so my other weapon must be equipped ;) thank you for your great work, Support and super fast response

**Comment by Reetus** [comment]
Correct...

```py
if not FindLayer("OneHanded") or GetAlias('found') != 0x40e7d51d:
	EquipItem(0x40e7d51d, "OneHanded")
```
