### ISSUE TITLE
"Lesser Artifact" Attribute not working with autoloot

### ISSUE THREAD

**Issue by RedSunset84** [Reetus/ClassicAssist#341]
Added via "Define custom Property" the "Lesser Artifact" property and want to auto loot "Lesser Artifact" items. Legendary, Major and Greater Artifacts items work with auto loot but my custom Lesser artifact is not working :(

Using newest version of classicuo with newest version of classisassist.

**Comment by Reetus** [comment]
Shard?

**Comment by RedSunset84** [comment]
official OSI/EA servers

**Comment by RedSunset84** [comment]
working now ... sorry was my fault, I did not uncheck the "argument" checkbox ... what is the argument value doing?
thank you very much for your help!
