### ISSUE TITLE
Docs request: All commands/explanations/snippets on one page

### ISSUE THREAD

**Issue by gzozulin** [Reetus/ClassicAssist#35]
When looking for a specific command/definition it is helpful to use search across the whole commands. Therefore it will be great to have all of them in one spot.

**Comment by Reetus** [comment]
https://github.com/Reetus/ClassicAssist/wiki/Macro-Commands

**Comment by gzozulin** [comment]
@Reetus yes, precisely,
but each group is on its own page and it is uncomfortable to search through them when you are looking for details,
for example, https://github.com/Reetus/ClassicAssist/wiki/Abilities#ClearAbility

**Comment by Reetus** [comment]
It was originally on 1 page but I had to split it up because GitHub would periodically say 'Page took too long to render'

I'll think of some other solution
