### ISSUE TITLE
Cannot launch assist with ClassicUO

### ISSUE THREAD

**Issue by gzozulin** [Reetus/ClassicAssist#360]
**Information**
- ClassicUO Version: 0.1.11.85
- ClassicAssist Version: 0.4.418
- Client Version: 5.0.8.3
- Shard: Renaissance
- OS: Ubuntu

Added the Assist via the ClassicUO launcher, it was identified, but it is not launching :(
The game is launching with no problems.

![Screenshot from 2023-06-11 00-42-47](https://github.com/Reetus/ClassicAssist/assets/3765610/4b434036-949c-49ad-af89-ddec51f3cfc0)

**Comment by KevinEady** [comment]
ClassicAssist does not work with Linux (or Mac OS X).
