### ISSUE TITLE
Screen Reduction Bug

### ISSUE THREAD

**Issue by Unstable-Kitsune** [Reetus/ClassicAssist#361]
**Information**
- ClassicUO Version: 0.1.11.86
- ClassicAssist Version: 0.4.418
- Client Version: 7.0.98.1
- Shard: Abysmal Isle -or- Any

**Describe the bug**
Screen UI Reduction to very tiny almost unreadable. It seems Classic Assist Reduces my screen UI Size to Tiny. Seems to do it no matter what version i use or way i launch it, or server i connect to. 

**To Reproduce**
1. Launch ClassicUO Client via Shortcut.
2. Click on 'Play'
3. Login to server.

**Expected behavior**

**Screenshots**
Left is Without Assist | Right is with. 
![image](https://github.com/Reetus/ClassicAssist/assets/116420714/172e5d32-dcee-42ad-be8b-859948240a6f)

**Comment by ibsavage** [comment]
@Unstable-Kitsune I Found a workaround on Discord provided by @Reetus that might be related:

> Wpf messes with the scaling
> You can set an option under properties

![scaling](https://github.com/Reetus/ClassicAssist/assets/8901177/6e64e787-9799-4cae-a143-8bed8ed59401)
([source](https://discord.com/channels/458277173208547350/685864489266053193/749753529467404368))

**Comment by Unstable-Kitsune** [comment]
Omg Thank you! i dont know why i didnt think of that
