### ISSUE TITLE
adding shard to list 

### ISSUE THREAD

**Issue by rizzen76** [Reetus/ClassicAssist#38]
how do i get shard added to list of shards you have on there wont let me connect to one thats not on there

**Comment by Reetus** [comment]
![image](https://user-images.githubusercontent.com/6239195/87884267-e14ea700-ca3f-11ea-8632-ab79cfc15ac0.png)

Did you click the add button and fill in the details?

**Comment by rizzen76** [comment]
sooo i got it added but im getting stuck on versifying on server and the server its self is fine

**Comment by Reetus** [comment]
What is the server, I will try it

**Comment by rizzen76** [comment]
nvm we figured it out thxs for help got it too work
