### ISSUE TITLE
Organizer Agent set to backback should ignore the container it sorts to if it is in the backpack

### ISSUE THREAD

**Issue by honestaly** [Reetus/ClassicAssist#385]
**Information**
- ClassicUO Version:  0.1.11.112
- ClassicAssist Version:  0.4.423
- Client Version: OSI Classic Client Standard
- Shard:  Baja

**Describe the bug**
Trying to create an agent that takes all the purchased blank Runes and puts them in a bag in my backpack
The agent when running eventually completes, but it first tries to put the 70 runes I have back into the bag they are already in.

**To Reproduce**
1. Go to a mage store and buy runes
2. Create an agent to take runes from your backpack and put them in a bag in your backpack
3. Go to another mage store and buy more runes
4. re-run the agent, see that it gets stuck first sorting the runes in the bag back to the bag, and then eventually gets the new one.

**Expected behavior**
Ignore the items already in the destination container

**Screenshots**
N/A

**Comment by Reetus** [comment]
Fix will be released in an upcoming release (if destination container is in source container, it won't organize the items that are descendants of the destination container)

Thank you for your report
