### ISSUE TITLE
Count Agent doesn't count Runes

### ISSUE THREAD

**Issue by honestaly** [Reetus/ClassicAssist#386]
**Information**
- ClassicUO Version: 0.1.11.112
- ClassicAssist Version:  0.4.423
- Client Version:  OSI Standard Classic
- Shard:  Baja

**Describe the bug**
Added a Count Agent to count blank runes, I have a backpack full of them, the organizer can organize them fine.
Count is Zero

**To Reproduce**
1. Create a Counters Agent for Blank Runes
2. Fill your backpack with Blank Runes
3. Click Recount
4. See that the count is zero

**Expected behavior**
It should show a number equal to the number of blank runes (or all my runes if marked and unmarked ons count the same)

**Screenshots**

![image](https://github.com/Reetus/ClassicAssist/assets/88744339/95f29f77-83fb-4d60-83d1-21563f785a35)

**Comment by Reetus** [comment]
This is OSI specific where the container contents / container contents update packet has 0 for the amount, it was expected to be 1 for a single item...

![image](https://github.com/Reetus/ClassicAssist/assets/6239195/5e729bc3-e5d5-4742-9dbe-2ec5e931e599)

Fix will be released in an upcoming release, thanks for your report
