### ISSUE TITLE
Profile not saving macros

### ISSUE THREAD

**Issue by RodVIII** [Reetus/ClassicAssist#39]
I have about 46 macros here and every time I change one or make a new and hit the save button (both on macros and on profile), it does not save anything... It only saves when I create a new profile (as a dupe) with the macros I just modified.

**Comment by Reetus** [comment]
Do you have multiple clients open with the save profile?

**Comment by RodVIII** [comment]
Nope. Only one client. My profile is used by 3 accounts, but they are never online at the same time.

**Comment by Reetus** [comment]
Reopen if still an issue
