### ISSUE TITLE
Crashes CUO Client back to Launcher on Launch

### ISSUE THREAD

**Issue by honestaly** [Reetus/ClassicAssist#454]
**Information**
- ClassicUO Version:  1.1.0.0
- ClassicAssist Version:  4.425.16
- Client Version: 7.0.104.7
- Shard: Baja

**Describe the bug**
After updating to the release of CUO on 2024-08-14 logging into a shard with CA enabled results in a freeze with half the graphic assets drawn and then the client crashes back to the launcher

**To Reproduce**
1. Update CUO to 1.1.0.0
2. Enable latest release of CA
3. Update Classic Client to 7.0.104.7
4. Log into OSI shard
5. Crash back to CUO Launcher

Confirmation:
1. Turn off CA
2. Log into OSI shard with same versions as above
3. able to login and play.  

**Expected behavior**
The behavior of the Confirmation steps with CA enabled should continue to work.  If a macro exists with reflection in it.   Disable the macro, but not crasht he client.

**Comment by Reetus** [comment]
Fixed in https://github.com/Reetus/ClassicAssist/releases/tag/4.425.17
