### ISSUE TITLE
Not loading profiles properly

### ISSUE THREAD

**Issue by chiconanni** [Reetus/ClassicAssist#47]
I dont know how to reproduce, but sometimes when i log in, profile loads to proper character, and sometimes not. Ty in advance

**Comment by Reetus** [comment]
It loads the last used profile unless this button is clicked to link the profile to the character...

![image](https://user-images.githubusercontent.com/6239195/89346980-81612d00-d6dc-11ea-98cf-27acdbcd33f4.png)

Are you linking the profile to the character?

**Comment by chiconanni** [comment]
Tried both! Sometimes dont work! just that!
![image](https://user-images.githubusercontent.com/69136836/89348732-7201c580-d683-11ea-860a-069bd3ddd0a9.png)

**Comment by chiconanni** [comment]
Notice that happens when i log a second client using CA too
