### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by talonair** [Reetus/ClassicAssist#51]
I've tried every dll I can find to use as a plugin (zlib64/32 & cuoapi) but none of them load. Am I doing something wrong?

**Comment by talonair** [comment]
And I don't see any EXE in the folders either?

**Comment by Reetus** [comment]
You're doing something wrong, you're probably downloading the source code and not the release...

[https://github.com/Reetus/ClassicAssist/releases/download/0.3.35.225/ClassicAssist.zip](url)

![image](https://user-images.githubusercontent.com/6239195/89715201-c6d07380-d9d6-11ea-870c-e497f5f3644a.png)

ClassicAssist.dll is the plugin that needs to go into ClassicUO's settings.json

Or you can use ClassicAssist.Launcher.exe to configure the settings.json

Refer to installation video...

[https://www.youtube.com/watch?v=SQ5QhR1TS1U](url)

**Comment by talonair** [comment]
Thanks, Reetus. I thought that could be the case but i couldn't find
anything else to download. Sorry to bother you, & thanks for the hard work!
