### ISSUE TITLE
Hits()/DiffHits() not working properly on Pets

### ISSUE THREAD

**Issue by TitanBalls** [Reetus/ClassicAssist#59]
I am trying to write a bandage macro for my pets.

The pet I use has 196 Hits. Hits() returns 25

I use this test code to check the Hits:
def TestLoop():
	_pet1 = Engine.Mobiles.Where(lambda m: m!= None
									and m.Name == Pet1Name).FirstOrDefault()
	Msg(str(Hits(_pet1)))

When in combat, my pet has 179/196. DiffHits should be 17, but returns 0

I use this test code to check the DiffHits:
def TestLoop():
	_pet1 = Engine.Mobiles.Where(lambda m: m!= None
									and m.Name == Pet1Name).FirstOrDefault()
	Msg(str(DiffHits(_pet1)))

**Comment by Reetus** [comment]
What shard/client version/etc
