### ISSUE TITLE
Some little problems..

### ISSUE THREAD

**Issue by Apellamen** [Reetus/ClassicAssist#6]
#fix#to Insert the "WaitForJournal" directly from the comandlist, it writes "WaitForJounal" in the script. it's mistyped.

#bug#when I push special buttons on the keyboard, sometimes the assistant starts to spams ALL MACROS togheter (keys like VolumeUP, Pause/Play)

**Comment by Apellamen** [comment]
note about the ESC button problem: it drops INT (not STR). I guess are my int4 boots. But i have nothing binded on ESC. And no Dress configuration with only the boots. (boots are present only in the Fullequip dress agent, together other items)

**Comment by Apellamen** [comment]
never mind. we resolved on disco

**Comment by Reetus** [comment]
WaitForJournal fixed a while ago...
