### ISSUE TITLE
Allow setting hotkeys to use all 3 modifier keys: Ctrl Shift Alt 

### ISSUE THREAD

**Issue by therealgorgan** [Reetus/ClassicAssist#60]
I can't set any hotkeys to anything but a 1-modifier combination.. meaning I can only do Ctrl+F or Alt+F but not Ctrl+Alt+F

**Comment by Timorio** [comment]
I'd like to reiterate the importance of this feature.  In the meantime, though, people can use AutoHotKey to use their preferred key combinations.

**Comment by Reetus** [comment]
This is implemented now
