### ISSUE TITLE
Icons and menus that can't be closed

### ISSUE THREAD

**Issue by ifeelrobbed** [Reetus/ClassicAssist#61]
I am unable to close the following menu and icons in game:
![unknown](https://user-images.githubusercontent.com/67766369/95229149-d8ab7880-07c5-11eb-93d5-44b99235b388.png)

Restarting CUO removes the empty menu, but the 2 icons remain. Right click does not work, nor does alt+right click.

Loading with CUO with ClassicAssist removed from settings.json does not show them. Loading CUO with ClassicAssist added back to settings.json shows them again.

**Comment by d0tsd0tsd0ts** [comment]
DId u try to unset these at Options Tab and restart classic assistant ?
![image](https://user-images.githubusercontent.com/1846503/95239362-39947a00-07e1-11eb-98d6-9177f7d16375.png)

**Comment by ifeelrobbed** [comment]
Ah ha. Somehow overlooked that. Looking good now.
