### ISSUE TITLE
Freezing and Fps Dropping Issues

### ISSUE THREAD

**Issue by d0tsd0tsd0ts** [Reetus/ClassicAssist#63]
Freezing Issues

I've just tested with Hotkey and Macro Tab... 

I will show u one example for testing and reproducing:
1) Image
![image](https://user-images.githubusercontent.com/1846503/95393736-750e7180-08d1-11eb-8543-ad774c34665f.png)
2) Code:
```
#Set DO NOT AUTO INTERRUPT
#Show all names
if not TimerExists("shownames"):
    SetTimer("shownames", 0)
elif Timer("shownames") > 5000:
    ShowNames("mobiles")
    SetTimer("shownames", 0)
ClearTargetQueue()
#Last Target
if not Paralyzed("self"):
    Target("last",1,1)
Pause(50)
```

If u run this macro without change Macro Tab to Options Tab, u will get some freezes and fps dropping. I've already tested with  25ms Limit Wheel Trigger set and unset and I still freezing when I'm Macro Tab or Hotkey Tab... 

So, u will be able to avoid it, changing to Options Tab, but it's just working when ClassicUO + ClassicAssist Memory is < 800-900 MB at Task Manager. 

![image](https://user-images.githubusercontent.com/1846503/95394674-60cb7400-08d3-11eb-95d3-300c432ffb2a.png)

When ClassicUO + ClassicAssist Memory is >= 800-900 MB as image. This trick wont work anymore... 

![image](https://user-images.githubusercontent.com/1846503/95394182-5066c980-08d2-11eb-824e-e702e38b3976.png)

My notebook is Acer Predator (i7700hq, 16gb, Samsung Evo, GF 1060).

**Comment by d0tsd0tsd0ts** [comment]
it's possible to force clear memory loaded as macro, targets, keys, uses and packets queue?

**Comment by d0tsd0tsd0ts** [comment]
It's not normal .... Memory is upping +1gb and when I put on hotkey tab or macro tab and press some hotkey or mouse wheel, my fps is dropping and screen is freezing

**Comment by d0tsd0tsd0ts** [comment]
![image](https://user-images.githubusercontent.com/1846503/97629200-84826580-1a0c-11eb-9594-09271c939190.png)

**Comment by d0tsd0tsd0ts** [comment]
Its happening with 1 hour opened

**Comment by Reetus** [comment]
To set the correct mouse wheel retrigger depending on your mouse, write a macro that does a HeadMsg('a') and see how many times it triggers, tweak retrigger delay until it only triggers once

The UI effect in macros tab of highlighting the running macro could cause a freeze if triggering alot in rapid succession

**Comment by d0tsd0tsd0ts** [comment]
I will test but It's not mouse wheel retrigger because it happens with hotkey from my keyboard... 

if u lose macro/hotkey tab focus to option tab, u will use ur mouse normally, but if u put focus on macro/hotkey tab, u will get a lot freeze and fps dropping
