### ISSUE TITLE
Shield Dress/Undress

### ISSUE THREAD

**Issue by d0tsd0tsd0ts** [Reetus/ClassicAssist#65]
It's not working as intended... 

If u set hotkey for dress/undress, classic always is undressing onehanded, because it is understanding as TwoHanded

**Comment by d0tsd0tsd0ts** [comment]
Shield Dress / Undress by Dress Tab are working good, but Shield Dress / Undress by Dress Tab by Hotkey arent!

![image](https://user-images.githubusercontent.com/1846503/97051588-cb2c1780-1555-11eb-94df-ac97d23cbdfe.png)

![image](https://user-images.githubusercontent.com/1846503/97051690-fc0c4c80-1555-11eb-805c-f1c256700e91.png)

**Comment by d0tsd0tsd0ts** [comment]
I needed to write a macro

```
if FindLayer("TwoHanded"):
	Undress("Weapon 2")
else:
	Dress("Weapon 2")
while Dressing():
	pass
```

**Comment by Reetus** [comment]
![ClassicAssist-2020-10-30-13-17-57](https://user-images.githubusercontent.com/6239195/97662545-5bb4ab80-1ab2-11eb-920f-fd4f0eaba6b8.gif)
Enable move conflicting items

**Comment by d0tsd0tsd0ts** [comment]
@Reetus Try it to dress/undress only shield

**Comment by d0tsd0tsd0ts** [comment]
eg ... Try to remove shield and stay with katana on hands

**Comment by d0tsd0tsd0ts** [comment]
When I've tested my book dropped instead of shield
