### ISSUE TITLE
Search level for FindTpye

### ISSUE THREAD

**Issue by Batt11** [Reetus/ClassicAssist#69]
Not sure where to ask this, hopefully this is the correct place. I am trying to search my bag for a specific type, but only the top layer. I can do this with the FindObject using 0 for the search level, Find type does not seem to have this argument. when I do a FindType, it always finds the objects in the nested bags. Is it possible to add a search level argument to FindType as it is in FindObject?

**Comment by Reetus** [comment]
https://github.com/Reetus/ClassicAssist/wiki/Entity#findtype

You use range for the search level when the findLocation is a container
