### ISSUE TITLE
Some possible features

### ISSUE THREAD

**Issue by Apellamen** [Reetus/ClassicAssist#7]
#Feature# ON/OFF Agents commands for Vendors/Scavenger/Autoloot

#Feature# Possibility to save, activate and deactivate, different Scavangers. Similar to organizers.

**#Feature# A section where to insert 1 or more passive loop scripts in BG (like YokoInjection). Add to any single script the bandage script isn't so user friendly...**  

#Feature# May the new writing support system be active after other commands? Just an idea. Dunno if it's intended.
![image](https://user-images.githubusercontent.com/47136830/74544649-d6708180-4f8a-11ea-9ffa-2f5748ee5250.png)

**Comment by Reetus** [comment]
> **#Feature# A section where to insert 1 or more passive loop scripts in BG (like YokoInjection). Add to any single script the bandage script isn't so user friendly...**

Not anytime soon.

> 
> #Feature# The assistant shouldn't close if pressing for mistake the X button if the client is still open.

Implemented in c706621614c3575863e3eee5fd3ecb06d3bba44e
> 
> #Impossibile Feature# Weapon specials icons don't activate (no red effect) when activted by scripts: I know, you already said me that's is a CUO side problem. This is only a reminder, maybe you will have stroke of genius and find a claver solution (like custom icons on steam only for activable stuff)

Implemented in 53d55b8f85dbff1e2df34b7fdbe76c9fbdab05c0

**Comment by Reetus** [comment]
Background macros in 6c4e0a2f7cc424ee2322570eef87e6dbfd84d957
