### ISSUE TITLE
No PopList feature

### ISSUE THREAD

**Issue by Grok0** [Reetus/ClassicAssist#71]
Coming from Steam, I make heavy use of PushList & PopList features. No PopList means that a ton of my preexisting (and many others preexisting macros) cannot be ported & functional without heavy workaround.

Looking forward to using ClassicAssist more and more in the future, having a blast with it thus far.

**Comment by Reetus** [comment]
https://github.com/Reetus/ClassicAssist/wiki/Lists#PopList
