### ISSUE TITLE
ClassicAssist doesn't recognize logs after some time LJing

### ISSUE THREAD

**Issue by Grok0** [Reetus/ClassicAssist#73]
Basically I wrote a script for recall Lumberjacking and after dropping off the first batch of Logs, the next batch I get ClassicAssist just.. can't see, for some reason. 

I know it's not my script because I can stop the script and try to objectinspect the logs, and nothing happens. If I try to add them to any kind of Agent, it says "Target Object...", I click the logs and then it says "Cannot Find Item..." The item is quite literally not visible to ClassicAssist UNTIL I manually move the logs around my backpack. Once they're manually manipulated, and registered in my backpack, they can be manipulated with ClassicAssist once again with no issues.

If this happens with Lumberjacking, I imagine it would happen with ANY type of resourcegathering, notably mining and lumberjacking.

EDIT:: I even tried baking Resync() into my macros before trying to find & manipulate the logs in my backpack, which usually works for UOSteam when this happens, and it doesn't fix it.

**Comment by Reetus** [comment]
Try with UseObject('backpack') before looking for the items

Otherwise post your macro and the shard you're playing on

**Comment by Grok0** [comment]
UseObject('backpack') worked. Surprisingly something I hadn't considered - thank you.
