### ISSUE TITLE
Feature Request: autotargetenemy

### ISSUE THREAD

**Issue by RodVIII** [Reetus/ClassicAssist#75]
Hello. Is it possible to add the autotargetenemy/self/friend on Classic Assist? Just like it is in UOSteam?

**Comment by d0tsd0tsd0ts** [comment]
What do u need to do ? I think that there has autotarget...

Eg:

Cast('Heal','self')
Cast('Heal','friend')
Cast('Heal','enemy')

it's auto target...

**Comment by RodVIII** [comment]
It does, but only for spells. If I use a scroll, I will have to use waitfortarget and target. Something like this:

UseType(0x1f5f)
WaitForTarget(1000)
Target("Enemy")

With autotargetenemy would be:
Autotargetenemy
UseType(0x1f5f)

**Comment by d0tsd0tsd0ts** [comment]
But it's the same, not ?

**Comment by d0tsd0tsd0ts** [comment]
Target("enemy",1,1)
UseType(0x1f5f)

Try it

**Comment by Reetus** [comment]
Whats the problem with use/waitfortarget/target?

**Comment by d0tsd0tsd0ts** [comment]
Maybe, he is using spell scroll, but he can use WaitForTargetOrFizzle()
