### ISSUE TITLE
[Feature Request] Make all text in object inspector copyable

### ISSUE THREAD

**Issue by bittiez** [Reetus/ClassicAssist#83]
It would be much easier if I could copy and paste object id's instead of typing them(just a small QOL thing, nothing super important)

**Comment by Reetus** [comment]
Isn't it already with ctrl-c?

**Comment by bittiez** [comment]
I apologize for not checking more thoroughly, I assumed because I couldn't select the text that wouldn't work 🤦‍♂️  Thank you though!
