### ISSUE TITLE
Assistant doesn't properly recognize enemy mobiles.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#89]
This always returns false:
```
PromptAlias( 'mobile' )
SetEnemy( 'mobile' )
if Enemy( 'mobile' ):
    print( 'true' )
else:
    print( 'false' )
```

**Comment by d0tsd0tsd0ts** [comment]
what would u like to do ?

**Comment by Reetus** [comment]
It's only mean't to return true if the notoriety is Enemy (Orange health bar)

**Comment by d0tsd0tsd0ts** [comment]
if u want to check object, u could use FindObject('mobile') or FindObject('enemy'), because u setted enemy
