### ISSUE TITLE
Backslash key (Oem5) doesn't work for hotkeys and macros.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#91]
Assistant Version: 0.3.189.256

The hotkey can be set, but does nothing when used.

**Comment by d0tsd0tsd0ts** [comment]
Which hotkey is it ? (Oem5) ?

**Comment by Timorio** [comment]
> Which hotkey is it ? (Oem5) ?
\
Backslash

**Comment by Timorio** [comment]
> Which hotkey is it ? (Oem5) ?
No hotkey or macro works when set to trigger on pressing backslash.  Oem5 is what the assistant calls the backslash key.
