### ISSUE TITLE
Invalid gump...

### ISSUE THREAD

**Issue by badungi** [Reetus/ClassicAssist#94]
Other Gump method work fine...
Only the InGump method does not work.
The client language is Korean.

What is the problem?

![11331133](https://user-images.githubusercontent.com/77443721/104591932-c25c6500-56b0-11eb-94cb-98364f89004d.png)

**Comment by Reetus** [comment]
What shard?

**Comment by badungi** [comment]
> What shard?

It is a Korean server called Margo operated by RunUO.

**Comment by Reetus** [comment]
> > What shard?
> 
> It is a Korean server called Margo operated by RunUO.

whats the login server address / website?

**Comment by badungi** [comment]
> > > What shard?
> > 
> > 
> > It is a Korean server called Margo operated by RunUO.
> 
> whats the login server address / website?

http://lod.me/lod/

**Comment by badungi** [comment]
> > > > What shard?
> > > 
> > > 
> > > It is a Korean server called Margo operated by RunUO.
> > 
> > 
> > whats the login server address / website?
> 
> http://lod.me/lod/

lod.so.tl:2594

**Comment by Reetus** [comment]
![image](https://user-images.githubusercontent.com/6239195/105657736-08f75e00-5f00-11eb-8f79-e4f73c7dd112.png)

In my testing it was only showing Invalid Gump when the text was not found, and InGump works?

**Comment by badungi** [comment]
At least in my situation InGump didn't work for anything.

If you don't find the text as mentioned and you get an Invalid gump

Can't I make it return false instead of an Invalied gump?

**Comment by Reetus** [comment]
yes, I will have a fix out shortly

**Comment by badungi** [comment]
> yes, I will have a fix out shortly

Thank you for your service :D

**Comment by Reetus** [comment]
I've also added this option...

![image](https://user-images.githubusercontent.com/6239195/105663172-8a54ed80-5f0c-11eb-863f-f36e44462d5b.png)

When checked it will use the Cliloc language setting from ClassicUO, so you can use Korean language for InGump/etc

![image](https://user-images.githubusercontent.com/6239195/105663209-a193db00-5f0c-11eb-929b-75778ff78f6c.png)
