### ISSUE TITLE
Scrolling the mousewheel causes the assistant and client to temporarily hang.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#95]
CUO: 0.1.6.135
Assistant: 0.3.194.262

**Comment by d0tsd0tsd0ts** [comment]
Hang = Stucks/Graphic Freezes ?

**Comment by Timorio** [comment]
Yes, it manifests as a mini-freeze for the client and a longer freeze for the assistant (and seems cumulative).  Switching between tabs doesn't seem to help.

**Comment by d0tsd0tsd0ts** [comment]
U need to put on Options Tab. I got it too and reported too but it was closed

**Comment by Timorio** [comment]
https://youtu.be/JduHAAJ6cVo
As you can see, the Options tab doesn't solve the issue.

**Comment by ziox-b** [comment]
Same issue.

**Comment by d0tsd0tsd0ts** [comment]
https://github.com/Reetus/ClassicAssist/issues/63

**Comment by qkdefus** [comment]
I redirected my mouse keys with logitech software i.e scroll up to Ctrl+num8, that temp solved the problem  for me

**Comment by Reetus** [comment]
@KevinEady did you want to check this one? last time i looked it was because one scroll on the wheel was sending like 100 OnMouse from ClassicUO, hence the minimum retrigger option

**Comment by qkdefus** [comment]
[https://puu.sh/H9MlW/c54bddde2e.gif](url)

**Comment by d0tsd0tsd0ts** [comment]
Dont let focus on MacroTab/HotkeyTab/SkillTab because u will get a lot graphic freezes... 

i've reported it 
https://github.com/Reetus/ClassicAssist/issues/63

Probably, It should be highlight ... If I remember when Steam was developing, it had same kind of problem and it was highlight from macro execute ...

**Comment by d0tsd0tsd0ts** [comment]
------ About Macro tab freeze  ------- 
I removed what reetus asked and replaced method too and got freeze. I've tested about 5 min

![image](https://user-images.githubusercontent.com/1846503/109441074-00200d80-7a13-11eb-8de8-988ffed4aeec.png)


`Reetus: or replace SetProperty in BaseViewModel.cs with this...

        public virtual void SetProperty<T>( ref T obj, T value, [CallerMemberName] string propertyName = "" )
        {
            if ( obj != null && obj.Equals( value ) )
            {
                return;
            }

            obj = value;
            NotifyPropertyChanged( propertyName );
        }`

- **With hotkey** -> freezes stopped  (if I stay on macro tab )
- **With mousewheel** -> freezes continue (but if i change tab to options tab, i will be able to use mousewheel without freeze)

**Comment by Reetus** [comment]
Assuming doesn't happen anymore as no one has cried for a while
