### ISSUE TITLE
object "found" updated suppression

### ISSUE THREAD

**Issue by nullerror** [Reetus/ClassicAssist#96]
This is an amazing app!

For the message: System: Object "found" updated...

Is there already a way to suppress this method built into the UI somewhere?

**Comment by d0tsd0tsd0ts** [comment]
Try to set **Macro default to quiet mode**

![image](https://user-images.githubusercontent.com/1846503/104819204-c1d7e180-580a-11eb-9b08-388258331084.png)

**Comment by nullerror** [comment]
Thanks. I will try that!
