### ISSUE TITLE
Exploring objects?

### ISSUE THREAD

**Issue by nullerror** [Reetus/ClassicAssist#97]
What is the best way to explore objects like Engine.Player.* for more advanced automation like it shows under the "advanced macros" wiki? So far I have just been using the Print statement to output to the UO window and that is not ideal.

**Comment by d0tsd0tsd0ts** [comment]
It depends. What would u like to write?

**Comment by nullerror** [comment]
I guess its more of a general question to see what properties are available as I carve out whatever ideas I have. The question came up when I was creating a function to check if a weapon was equipped, and if not to equip one of a specific type if in backpack. This was mostly to get around the journal spam of using FindType but that could be solved with running macros in quiet mode.

**Comment by KevinEady** [comment]
The easiest way IMO is to download the source and explore it. Everything coded inside the C# application is available within Python.

For example, the [`TileData`](https://github.com/Reetus/ClassicAssist/blob/master/ClassicAssist/UO/Data/TileData.cs#L7) class has methods to [retrieve tile information](https://github.com/Reetus/ClassicAssist/blob/master/ClassicAssist/UO/Data/TileData.cs#L174). 

```py
from ClassicAssist.UO.Data import TileData, TileFlags
TileData.GetStaticTile( 0x9b2 ).Flags.HasFlag( TileFlags.Container ) # True: 0x9b2 is backpack, which is a container 
```

You can just find these methods by searching around inside the C# code. Hope this helps.

**Comment by nullerror** [comment]
Thanks. I have been looking around the source already but I need to brush up ony c#. Its been about 5 years. Thanks for the example, that helps!
