### ISSUE TITLE
Run(), Walk(), and DirectionTo() execute too slowly and have poor in-game results.

### ISSUE THREAD

**Issue by Timorio** [Reetus/ClassicAssist#98]
Assist: 0.3.194.262
CUO: 0.1.6.135
Server: UOForever

These methods move the player so slowly when looped that they can't be relied on for any situation that requires speed.

**Comment by nullerror** [comment]
You want to use Pathfind() if you want to move quick. Unless you have "always run" ticked on the client, you need to move minimum of 15 tiles to run iirc. Your best bet is to make a custom function that uses a mix of Pathfind() and those other movement functions IMO.

**Comment by Timorio** [comment]
Why is it like this, though?  Can't it be fixed?

**Comment by nullerror** [comment]
> 
> 
> Why is it like this, though? Can't it be fixed?

Not sure, I did not help develop this but I think it has something to do with having to verify that the player actually moved. If you don't verify the player moved from the client side, then you are just spamming the server with invalid movement packets. When you do this with ClassicAssist, it causes some CPU issues. I made the def below when playing around with movement. I think probably it has to be taken care of on a level that requires tracking of movement packets and getting coordinates back from the server.

def MoveTiles(direction, tiles):
		
	x = X('self')
	y = Y('self')
	
	for i in range(0,tiles):

		if direction == "west": # Subtract X
			x = X('self') - 1
		if direction == "east": # Add X
			x = X('self') + 1
		if direction == "south": # add y
			y = Y('self') + 1
		if direction == "north": # subtract y
			y = Y('self') - 1
			
		before_x = X('self')
		before_y = Y('self')
		
		Pathfind(x,y,-1)
		
		# Play around with this value. Over 250 causes jerky running but 250 and under cause inconsistent reads of coordinates
		Pause(300)
		
		after_x = X('self')
		after_y = Y('self')
		
		# Comment these 3 lines out and try this when moving against an obstacle and watch your CPU usage spike.
		if after_x == before_x and after_y == before_y:
			print("Did not move. Stuck?")
			return # Didn't move, so exit out
		

MoveTiles("north",60)

**Comment by Timorio** [comment]
Thanks for the tip.  Hopefully they'll be able to figure out a solution to the problem.

**Comment by Reetus** [comment]
Use the Fastern Run example from public macros if you don't want to wait for the movement accepted packets

```py
# Name: Faster Run
# Description: Run without waiting for movement accepted packets to speed up movement
# Author: Reetus
# Era: Any

from Assistant import Engine
from ClassicAssist.UO import UOMath
from ClassicAssist.UO.Data import Direction

def DirectionTo(alias):
    mobile = Engine.Mobiles.GetMobile(GetAlias(alias))
    
    if mobile == None:
        return Direction.Invalid

    return UOMath.MapDirection( Engine.Player.X, Engine.Player.Y, mobile.X, mobile.Y )
    
def FRun(dir):
    if dir == Direction.Invalid:
        return
    Engine.Move(dir, True)    
    
while Distance('enemy') > 1:    
    FRun(DirectionTo('enemy'))
    Pause(100)
```
